server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: flashcards
    password: flashcards
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true